export const configOfFrameWorkAPIs = {
    createDraftFrameWork :'draftFrameworks/create',
    updateDraftFrameWork : "draftFrameworks/update/",
    draftFrameWorkList: "draftFrameworks/list",
    deleteDraftFrameWork: "draftFrameworks/delete/",
    draftCriteriaCreate: "draftCriteria/create",
    updateDraftCriteria:"draftCriteria/update/",
    listDraftCriteria:"draftCriteria/list/",
    draftCriteriaDelete:"draftCriteria/delete/",
    getDraftFrameWorkDetails:"draftFrameworks/details/",
    getEntityTypeList:"entityTypes/canBeObserved/",
    draftEcmCreate:"draftECM/create",
    draftSectionCreate:"draftSections/create",
    listDraftSection:"draftSections/list",
    listDraftEcm:"draftECM/list",
    draftCreateQuestion:"draftQuestions/create",
    updateDraftQuestion:"draftQuestions/update/",
    draftQuestionList:"draftQuestions/list/",
    deleteDraftQuestion:"draftQuestions/delete/",
    detailsDraftQuestion:"draftQuestions/details/"
}